{"uuid": "4d2c28f5-ad61-463f-9e43-4b9305cf93f6", "children": ["927db6b3-6db5-4d6b-84f0-e644a034da31"], "befores": [{"name": "_xunit_setup_class_fixture_TestMpArticle", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=115.0.5790.102)\n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\python.py\", line 853, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\python.py\", line 774, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\Python\\uiAutoTestHmtt\\scripts\\test02_mp_article.py\", line 9, in setup_class\n    driver = GetDriver.get_web_driver(page.url_mp)\n  File \"E:\\Python\\uiAutoTestHmtt\\tools\\get_driver.py\", line 17, in get_web_driver\n    cls.__web_driver.get(url)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 324, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 312, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1690203232343, "stop": 1690203234174}], "start": 1690203232343, "stop": 1690203234488}